apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-for-efk-pvc                  # azure-disk-sc
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS      # or Premium_LRS for premium disks
  kind: Managed                         # Managed or Unmanaged disks
  cachingmode: ReadOnly                 # Options: None, ReadOnly, ReadWrite
reclaimPolicy: Retain                   # Options: Retain, Delete, Recycle
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true              # true or false