apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-efk-elastisearch
  namespace: efklog  
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: sc-for-efk-pvc
  resources:
    requests:
      storage: 8Gi