apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
  labels:
    D: D
spec:
  selector: 
    matchLabels:
      A: A
      B: B
  template:
    metadata:
      labels:
        A: A
        B: B
        C: C
    spec:
      containers:
        - name: container-name
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
  #  A: A
  #  B: B
   C: C
  ports:
    - port: 80
      targetPort: 80
---