apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  # config-server-deployment 
  eureka_service_address: "http://eureka-0.eureka-internal-svc:8761/eureka"

--- 

apiVersion: v1
kind: ConfigMap
metadata:
 name: config-cm
data:
  # Source - config-server-deployment-service | UsedBy - cloud-gw-deployment 
  config_url: "http://config-server-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  hostname: "mysql-0.mysql"