apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-app
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
        - name: payment-service-app
          image: dailycodebuffer/paymentservice:latest
          ports:
            - containerPort: 8081
              name: payment-port
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_url

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: hostname
                  name: mysql-cm

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  type: ClusterIP
  selector:
    app: payment-service-app
  ports:
    - port: 80
      targetPort: payment-port