apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis-app
          image: redis:7.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis-port
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "no"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: ClusterIP
  selector:
    app: redis-app
  ports: 
    - port: 6379
      targetPort: redis-port
---