apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka-internal-svc # eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: dailycodebuffer/serviceregistry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
              name: service-port
---
# This is a internal Service - Provides stickiness.
apiVersion: v1
kind: Service
metadata:
  name: eureka-internal-svc
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - port: 8761
      name: eureka-internal-service-port
#      targetPort: 8761
---
# This is a external Service - Provides Load Balancing.
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb-svc
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
    - port: 80
      targetPort: service-port # 8761